export CONSUMER_KEY=3MVG9LBJLApeX_PA5tVomzpRsGko8Rbi.d.CTl4ZthGqcFt8sd2OZBcO5kd54MJDkV6tA4E9jnwJHlwpctfl6
export JWT_KEY_FILE=~/Desktop/travisCI/assets/server.key
export HUB_USERNAME=esteban@resourceful-goat-sxqr8i.com

